INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '적 영토에서 [ICON_MOVES]이동 속도 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR] 증가[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_SILENT_HUNTER_HELP', '공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+75%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '대양 타일에서 턴 종료 불가[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_FIRE_SUPPORT_HELP', '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_STEAM_POWERED_HELP', '연안 타일에서 [ICON_MOVES]이동력 [COLOR_POSITIVE_TEXT]두 배[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY_HELP', '해상 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_NEGATIVE_TEXT]-50%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '보이지 않음');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '잠수함 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+33%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_II_HELP', '잠수함 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+75%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_HEAVY_PAYLOAD_HELP', '도시 공격 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+50%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '헬리콥터 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+150%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY_HELP', '기마 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_NEGATIVE_TEXT]-33%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '기갑 유닛 대항 시 [ICON_STRENGTH]전투력 보너스 [COLOR_POSITIVE_TEXT]+100%[ENDCOLOR]');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '상대방 영토에 침입 가능');

INSERT INTO Language_ko_KR (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '공격 후 이동 가능[NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]');

---------------------------------------------
INSERT INTO Language_ko_KR (Tag, Text) 
SELECT 'TXT_KEY_BUILDING_SHRINE_HELP', '도시의 [ICON_PEACE]신앙이 [COLOR_POSITIVE_TEXT]2[ENDCOLOR] 증가합니다.'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings 
SET Help = 'TXT_KEY_BUILDING_SHRINE_HELP'
WHERE Type = 'BUILDING_SHRINE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

---------------------------------------------

UPDATE Language_ko_KR
SET Text = '명백한 운명'
WHERE Tag = 'TXT_KEY_TRAIT_RIVER_EXPANSION_SHORT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '산병을 대체하는 훈의 고유 유닛입니다. 빠른 원거리 유닛으로 평지에서 치명적입니다. 창병에 취약하나 [ICON_RES_HORSE]말 자원을 요구하지 않습니다.'
WHERE Tag = 'TXT_KEY_UNIT_HELP_HUN_HORSE_ARCHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );
 
UPDATE Language_ko_KR
SET Text = '그레이트 갈레아스'
WHERE Tag = 'TXT_KEY_UNIT_VENETIAN_GALLEASS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '테르시오를 대체하는 스웨덴의 고유 유닛입니다. 장거리 원정에 적합한 강력한 최전방 지상 유닛입니다.'
WHERE Tag = 'TXT_KEY_UNIT_HELP_SWEDISH_CAROLEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '나침반 필요'
WHERE Tag = 'TXT_KEY_PEDIA_PROMOTION_OCEAN_IMPASSABLE_ASTRO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '은폐 (잠수함)'
WHERE Tag = 'TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '적 유닛 처치 시 체력 회복 [COLOR_POSITIVE_TEXT]+25[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '시야 [COLOR_POSITIVE_TEXT]+1[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '시야 [COLOR_POSITIVE_TEXT]+2[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '시야 [COLOR_POSITIVE_TEXT]+3[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '시야 [COLOR_POSITIVE_TEXT]+4[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '적 유닛 처치 시 체력 회복 [COLOR_POSITIVE_TEXT]+25[ENDCOLOR][NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '험지로 이동 시 모든 [ICON_MOVES]이동력 소모[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]업그레이드 시 소멸[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ROUGH_TERRAIN_ENDS_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '포병대'
WHERE Tag = 'TXT_KEY_UNIT_ARTILLERY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

UPDATE Language_ko_KR
SET Text = '전략의 여신'
WHERE Tag = 'TXT_KEY_BELIEF_GODDESS_STRATEGY_SHORT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );